### ISSUE TITLE
Localization v1.0.0

### ISSUE THREAD

**Issue by arcanedev-maroc** [ARCANEDEV/Localization#31]
## TODO

  - [x] Refactoring/Renaming the contracts (interfaces).
  - [ ] Adding more regionals for locales.
  - [ ] Complete the documentation.

## GOALS

  - [ ] 100% Code coverage + Maximum code quality.

## Suggestions
- [ ] Adding the attributes translator (Helper / Trait) ??
- [ ] Extending the Locale Entity Class (https://github.com/ARCANEDEV/Localization/issues/49).

**NOTE :** Feel free to post any suggestion or a feature to improve this package.
